#!/bin/sh

# Reset Color
Off='\033[0m'

todo_file=$HOME/Scripts/mywiki/mywiki.md
todo_file_number_line=5

if [ -f $todo_file ]; then
  Todo="$(cat $todo_file | awk "FNR==$todo_file_number_line" | tr -d -)!"
else
  Todo="todo file is not found!"
fi

Black='\033[1;90m'
Red='\033[1;31m'
Green='\033[1;32m'
Yellow='\033[1;33m'
Blue='\033[1;34m'
Purple='\033[1;35m'
Cyan='\033[1;36m'
White='\033[1;37m'

echo "
       ${Yellow}A___A
      ( . . )
   ${Green},--${Yellow}U${Green}-----${Yellow}U${Green}--,  ${Blue}$(whoami)@$(cat /proc/sys/kernel/hostname)
   ${Green}|           |  ${Cyan}Uptime:${Purple}$(uptime -p)
   ${Green}| ${Blue}こんにちは${Green}|  ${Cyan}Date  :${Purple}$(date)
   ${Green};___________; ${Red}$Todo
       ${Yellow}| | |
        ${Yellow}U U
${Off}"
