#!/bin/sh
#
# this is custom script to control brightness with an icon and a bar level customed for dunst
#
# requirements:
# - dunst

# first declared vars
bar_length=302
brightness_path="/sys/class/backlight/amdgpu_bl0/brightness"
bright_level=$(cat "/sys/class/backlight/amdgpu_bl0/brightness")

# get an icon based on the brightness level
if [ $bright_level -le 36 ]; then
  icon="󰃚 "
elif [ $bright_level -le 72 ]; then
  icon="󰃛 "
elif [ $bright_level -le 108 ]; then
  icon="󰃜 "
elif [ $bright_level -le 145 ]; then
  icon="󰃝 "
elif [ $bright_level -le 182 ]; then
  icon="󰃞 "
elif [ $bright_level -le 218 ]; then
  icon="󰃟 "
else
  icon="󰃠 "
fi

# declare the value
if [ $bright_level -gt 246 ]; then
  Increase=$(($bright_level + $((255 - $bright_level))))
else
  Increase=$(($bright_level + 13))
fi
if [ $bright_level -lt 13 ]; then
  Decrease=$(($bright_level - $bright_level))
else
  Decrease=$(($bright_level - 13))
fi

# command
if [ "$1" = "--up" ]; then
  # increasing the volume as the same as $(xbacklight +5)
  echo $Increase | tee $brightness_path
elif [ "$1" = "--down" ]; then
  # decreasing the volume as the same as $(xbacklight -5)
  echo $Decrease | tee $brightness_path
fi

# redeclare the bar after Increasing or Decreasing process
bright_level=$(cat "/sys/class/backlight/amdgpu_bl0/brightness")
bright_level_percent=$(($bright_level*100/255))

# bar length is 300, which is match the dunst length 305 with the icon
bar_level_percent=$(($bar_length/100*$bright_level_percent))
bar="$(seq -s "─" 0 $(($bar_level_percent / 9)) | sed 's/[0-9]//g')"

# dunst notify-send
notify-send -r 500 -u normal "$icon $bar" -t 1200
